LINE_TYPE_UNKNOWN, \
    LINE_TYPE_NORMAL, \
    LINE_TYPE_TITLE, \
    LINE_TYPE_SECTION, \
    LINE_TYPE_SECTION_1, \
    LINE_TYPE_SECTION_2, \
    LINE_TYPE_SECTION_3, \
    LINE_IME = range(8)

debug = False
