
# relation between consecutive group
LP_SAME_LEVEL = 1
LP_SUP = 2
LP_SUB = 3
LP_BIGGER = 4 # from script back to normal
LP_OTHER = 5

REL_HOR, REL_RSUB, REL_RSUP, REL_LSUB, REL_LSUP, REL_UPPER, REL_UNDER = range(7)

G_T_NORMAL, \
G_T_RADICAL, \
G_T_FRACTION, \
G_T_SUP_SUB_SCRIPT, \
G_T_FENCE,\
G_T_NAMED_FUNC,\
G_T_BIN_OP,\
=range(7)
# all possible meaning of fence

ME_GROUP_NORMAL, \
ME_GROUP_RADICAL, \
ME_GROUP_FRACTION, \
ME_GROUP_SUPSUB, \
ME_GROUP_SUP, \
ME_GROUP_SUB,\
=range(6)


CHAR_NORMAL, \
CHAR_NORMAL_Y, \
CHAR_NORMAL_XY, \
CHAR_NORMAL_HXY, \
CHAR_NORMAL_YZ, \
CHAR_NORMAL_XYZ, \
CHAR_NORMAL_HXYZ, \
CHAR_IRREGULAR,  \
CHAR_IRREGULAR_CENTERED, \
CHAR_IRREGULAR_CENTERED_FIXED, \
CHAR_IRREGULAR_CENTERED_VARYING_SIZE, \
CHAR_IRREGULAR_CENTERED_VARYING_ASPECT, \
CHAR_IRREGULAR_NON_CENTERED \
=range(13)
